#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os
import sys
path = sys.path[0] 
parent_path = os.path.dirname(path) 
sys.path.insert(0,(parent_path))
import sqlite3
from sqlite_stock_dao import SqliteStockDao

class XueqiuDao(SqliteStockDao):
    def __init__(self,path,table):
        super(XueqiuDao,self).__init__(path,table)

    def get_parameter(self):
        parameter = [
            {'key_name':'symbol','type':'VARCHAR[20]','primary_key':True},
            {'key_name':'name','type':'VARCHAR[20]'},
            {'key_name':'symbol','type':'DOUBLE'},
            {'key_name':'name','type':'DOUBLE'},
            {'key_name':'mc','type':'DOUBLE'},
            {'key_name':'fmc','type':'DOUBLE'},
            {'key_name':'pettm','type':'DOUBLE'},
            {'key_name':'pelyr','type':'DOUBLE'},
            {'key_name':'eps','type':'DOUBLE'},
            {'key_name':'bps','type':'DOUBLE'},
            {'key_name':'roediluted','type':'DOUBLE'},
            {'key_name':'netprofit','type':'DOUBLE'},
            {'key_name':'dy','type':'DOUBLE'},
            {'key_name':'pb','type':'DOUBLE'},
            {'key_name':'current','type':'DOUBLE'},
            {'key_name':'pct','type':'DOUBLE'},
            {'key_name':'pct5','type':'DOUBLE'},
            {'key_name':'pct10','type':'DOUBLE'},
            {'key_name':'pct20','type':'DOUBLE'},
            {'key_name':'pct1m','type':'DOUBLE'},
            {'key_name':'chgpct','type':'DOUBLE'},
            {'key_name':'chgpct5','type':'DOUBLE'},
            {'key_name':'chgpct10','type':'DOUBLE'},
            {'key_name':'chgpct20','type':'DOUBLE'},
            {'key_name':'chgpct1m','type':'DOUBLE'},
            {'key_name':'volume','type':'DOUBLE'},
            {'key_name':'volavg30','type':'DOUBLE'},
            {'key_name':'amount','type':'DOUBLE'},
            {'key_name':'tr','type':'DOUBLE'},
            {'key_name':'tr5','type':'DOUBLE'},
            {'key_name':'tr10','type':'DOUBLE'},
            {'key_name':'tr20','type':'DOUBLE'},
            {'key_name':'tr1m','type':'DOUBLE'},
            {'key_name':'epsdiluted','type':'DOUBLE'},
            {'key_name':'epsweighted','type':'DOUBLE'},
            {'key_name':'ocps','type':'DOUBLE'},
            {'key_name':'cps','type':'DOUBLE'},
            {'key_name':'upps','type':'DOUBLE'},
            {'key_name':'sps','type':'DOUBLE'},
            {'key_name':'csps','type':'DOUBLE'},
            {'key_name':'beps','type':'DOUBLE'},
            {'key_name':'epsyg','type':'DOUBLE'},
            {'key_name':'epsqg','type':'DOUBLE'},
            {'key_name':'upqg','type':'DOUBLE'},
            {'key_name':'evps','type':'DOUBLE'},
            {'key_name':'tbi','type':'DOUBLE'},
            {'key_name':'bi','type':'DOUBLE'},
            {'key_name':'tbc','type':'DOUBLE'},
            {'key_name':'bc','type':'DOUBLE'},
            {'key_name':'bp','type':'DOUBLE'},
            {'key_name':'tp','type':'DOUBLE'},
            {'key_name':'np','type':'DOUBLE'},
            {'key_name':'pbt','type':'DOUBLE'},
            {'key_name':'tax','type':'DOUBLE'},
            {'key_name':'nbe','type':'DOUBLE'},
            {'key_name':'fe','type':'DOUBLE'},
            {'key_name':'ip','type':'DOUBLE'},
            {'key_name':'ca','type':'DOUBLE'},
            {'key_name':'nca','type':'DOUBLE'},
            {'key_name':'cl','type':'DOUBLE'},
            {'key_name':'ncl','type':'DOUBLE'},
            {'key_name':'tl','type':'DOUBLE'},
            {'key_name':'eq','type':'DOUBLE'},
            {'key_name':'teq','type':'DOUBLE'},
            {'key_name':'up','type':'DOUBLE'},
            {'key_name':'cur','type':'DOUBLE'},
            {'key_name':'fa','type':'DOUBLE'},
            {'key_name':'fan','type':'DOUBLE'},
            {'key_name':'li','type':'DOUBLE'},
            {'key_name':'rec','type':'DOUBLE'},
            {'key_name':'inv','type':'DOUBLE'},
            {'key_name':'ia','type':'DOUBLE'},
            {'key_name':'ta','type':'DOUBLE'},
            {'key_name':'cs','type':'DOUBLE'},
            {'key_name':'pc','type':'DOUBLE'},
            {'key_name':'fncf','type':'DOUBLE'},
            {'key_name':'incf','type':'DOUBLE'},
            {'key_name':'bncf','type':'DOUBLE'},
            {'key_name':'cnr','type':'DOUBLE'},
            {'key_name':'fcb','type':'DOUBLE'},
            {'key_name':'qr','type':'DOUBLE'},
            {'key_name':'cr','type':'DOUBLE'},
            {'key_name':'nag','type':'DOUBLE'},
            {'key_name':'roeweighted','type':'DOUBLE'},
            {'key_name':'mbig','type':'DOUBLE'},
            {'key_name':'nig','type':'DOUBLE'},
            {'key_name':'tag','type':'DOUBLE'},
            {'key_name':'sgpr','type':'DOUBLE'},
            {'key_name':'snpr','type':'DOUBLE'},
            {'key_name':'dar','type':'DOUBLE'},
        ]
        return parameter
        
